server:
  port: 8008
spring:
  banner:
    location: banner-dev.txt
  datasource:
    url: jdbc:mysql://192.168.7.125:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&useSSL=false
    password: o2otest2017
    username: o2ouser

#mybatis:
#  configLocation: classpath:mybatis-config.xml

eureka:
  instance:
    #单机hostname: localhost
    hostname: eureka7002.com         #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      #Eureka高复用时设置其他的Eureka之间通信
      #defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
      defaultZone: http://eureka7003.com:7003/eureka/
    #server:
    #enable-self-preservation: false   #Eureka服务端关闭心跳连接测试